# Generated by Django 3.1.1 on 2021-02-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_url',
            field=models.CharField(default='http://google.com/', max_length=256),
            preserve_default=False,
        ),
    ]
