# Generated by Django 3.1.1 on 2021-02-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0002_job_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=8192),
        ),
    ]
