# Generated by Django 3.1.1 on 2021-02-23 04:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0003_auto_20210222_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
